global:
  scrape_interval: 5s  # How often to collect metrics from targets

scrape_configs:
  - job_name: 'monitoring-app'  # Just a name for this group
    static_configs:
      - targets: ['host.docker.internal:5000']  # Your Flask app's metrics URL
